
---
# This playbook gives the user hc3 the rigths to shutdown the system

- lineinfile:
    dest: ~/.bashrc
    regexp: '^alias shutdown'
    line: "alias shutdown='sudo /sbin/shutdown'"
- lineinfile:
    dest: ~/.bashrc
    regexp: '^alias reboot'
    line: "alias reboot='sudo /sbin/reboot'"


