---
# This playbook deploys the whole Heating Control 3 application

- name: Install all componentes of HeatingControl 3
  hosts: all
  remote_user: hc3

  roles:
#OK    - kernelConfig
#ok  - remoteShutdown
#OK    - greeting
#ok    - docker
  - heatingControl
    #- heatingControlWebGui
