---

# This playbook installs a great Greeting Script that 
# executes at ssh login

- name: Copy Script to hc3 user
  template:
    src: "templates/welcome.sh"
    dest: "~"
    mode: u=rwx,g=rwx,o=rwx

- lineinfile:
    dest: /etc/profile
    regexp: '^/home/hc3/welcome.sh'
    line: '/home/hc3/welcome.sh'
  become: true

