
---

# This playbook installs a great Greeting Script that 
# executes at ssh login

- name: Copy Script to pi user
  template:
    src: "templates/welcome.sh"
    dest: "~"
    mode: u=rwx,g=rwx,o=rwx

- lineinfile:
    dest: /etc/profile
    regexp: '^/home/pi/welcome.sh'
    line: '/home/pi/welcome.sh'
  become: true

