---


# This playbook installs Heating Control

- name: Prune all dangling Volumnes
  shell: "docker system prune -f"
  become: yes

- name: Stop all docker-container
  shell: docker stop $(docker ps -aq) || true
  become: yes

- name: Cleanup docker container
  shell: "docker container prune -f"
  become: yes

# ------------------------------------------------------------------------------------------------------------------

- name: create Heating Control base dir
  file:
    path: /opt/heatingControl
    state: directory
    owner: pi
    group: root
    mode: 0775
  become: yes

- name: Copy Rabbit MQ config
  copy:
    src: templates/rabbit_aqmp_config.json
    dest: /opt/heatingControl/rabbit_aqmp_config.json

- name: Copy Rabbit MQ Admin
  copy:
    src: templates/rabbitmqadmin
    dest: /opt/heatingControl/rabbitmqadmin
    mode: u=rwx,g=r,o=r

- name: Copy docker-compose file
  copy:
    src: "templates/docker-compose.yml"
    dest: "/opt/heatingControl/docker-compose.yml"

- name: Pull docker images
  shell: "docker-compose -f /opt/heatingControl/docker-compose.yml pull"
  become: yes

- name: First start and configure RabbitMQ
  shell: "docker-compose -f /opt/heatingControl/docker-compose.yml up -d hc-aqmp"
  become: yes

- name: Wait for Rabbit MQ come up
  wait_for:
    port: 15672
    delay: 30

- name: configure rabbitmq via admin
  shell:
    cmd: "./rabbitmqadmin -q import rabbit_aqmp_config.json"
    chdir: "/opt/heatingControl/"

- name: Create containers
  shell: "docker-compose -f /opt/heatingControl/docker-compose.yml up -d"
  become: yes

#- name: Configure Rabbit MQ via Curl
#  shell: 'curl -u guest:guest \
#          -X POST -H "content-type:application/json" \
#          -d @/opt/heatingControl/rabbit_aqmp_config.json \
#          http://localhost:15672/api/definitions'
