---


# This playbook installs Heating Control

- name: Prune all dangling Volumnes
  shell: "docker system prune -f"
  become: yes

- name: Stop all docker-container
  shell: docker stop $(docker ps -aq) || true
  become: yes

- name: Cleanup docker container
  shell: "docker container prune -f"
  become: yes

# ------------------------------------------------------------------------------------------------------------------

- name: create Heating Control base dir
  file:
    path: /opt/heatingControl
    state: directory
    owner: hc3
    group: root
    mode: 0775
  become: yes

- name: create hc3-proxy config dir
  file:
    path: /opt/heatingControl/proxyConf
    state: directory
    owner: hc3
    group: root
    mode: 0775
  become: yes

- name: Copy Rabbit MQ config
  copy:
    src: templates/rabbit_aqmp_config.json
    dest: /opt/heatingControl/rabbit_aqmp_config.json

- name: Copy hc3-proxy config
  copy:
    src: templates/Caddyfile
    dest: /opt/heatingControl/proxyConf
    mode: u=rw,g=r,o=r

- name: Copy docker-compose file
  template:
    src: "templates/docker-compose.yml.y2"
    dest: "/opt/heatingControl/docker-compose.yml"

- name: Pull docker images
  shell: "docker-compose -f /opt/heatingControl/docker-compose.yml pull"
  become: yes

- name: First start and configure RabbitMQ
  shell: "docker-compose -f /opt/heatingControl/docker-compose.yml up -d hc3-aqmp"
  become: yes

- name: Wait for Rabbit MQ come up
  wait_for:
    port: 15672
    delay: 30

- name: copy hc3 config to hc3-aqmp container
  shell: "docker cp /opt/heatingControl/rabbit_aqmp_config.json hc3-aqmp:/tmp"

- name: import config with rabbitmqadmin
  shell: "docker exec hc3-aqmp rabbitmqadmin import /tmp/rabbit_aqmp_config.json"

- name: Create all not yet created containers
  shell: "docker-compose -f /opt/heatingControl/docker-compose.yml up -d"
  become: yes

