version: '2'
services:
   influxDB:
      image: influxdb:1.7
      container_name: influxDB
      restart: always
      hostname: influxDB
      ports:
         - 8086:8086
      volumes:
         - data-volume:/var/lib/influxdb

volumes:
   data-volume:
      driver: local
      driver_opts:
         type: none
         o: bind
         device: "/srv/dev-disk-by-label-Data/san/influxDB"