version: '3'
services:
   #-----------------------------------------------------------------------------------
   hc3-aqmp:
      image: ronnyroos/rpi-rabbitmq
      container_name: hc3-aqmp
      restart: always
      hostname: hc3-aqmp
      ports:
         - 5672:5672
         - 15672:15672
      logging:
         driver: "json-file"
         options:
            max-size: "1024m"
      network_mode: "host"
   #-----------------------------------------------------------------------------------
   hc3-sensor:
      image: jkarthaus/hc3-sensor:latest
      container_name: hc3-sensor
      restart: always
      hostname: hc3-sensor
      environment:
         - RABBIT_MQ_HOST=hc3-werkstatt
         - RABBIT_MQ_EXCHANGE=hc-ds18b20
      privileged: true
      depends_on:
         - hc3-aqmp
      logging:
         driver: "json-file"
         options:
            max-size: "1024m"
      network_mode: "host"
   #-----------------------------------------------------------------------------------
   hc3-actor:
      image: jkarthaus/hc3-actor:latest
      container_name: hc3-actor
      restart: always
      hostname: hc3-actor
      environment:
         - RABBIT_MQ_HOST=hc3-werkstatt
         - RABBIT_MQ_QUEUE=hc-gpio-actor
         - DEMO_MODE=False
      privileged: true
      depends_on:
         - hc3-aqmp
      logging:
         driver: "json-file"
         options:
            max-size: "1024m"
      network_mode: "host"
   #-----------------------------------------------------------------------------------
   hc3-display:
      image: jkarthaus/hc3-display:latest
      container_name: hc3-display
      restart: always
      hostname: hc3-display
      environment:
         - RABBIT_MQ_HOST=hc3-werkstatt
         - RABBIT_MQ_QUEUE=hc-lcd-display
         - DEMO_MODE=False
         - WELCOME_TEXT=Heating Control III...
      devices:
         - "/dev/i2c-1:/dev/i2c-1"
      depends_on:
         - hc3-aqmp
      logging:
         driver: "json-file"
         options:
            max-size: "1024m"
      network_mode: "host"
   #-----------------------------------------------------------------------------------
   hc3-core:
      image: jkarthaus/hc3-core:latest
      container_name: hc3-core
      restart: always
      hostname: hc3-core
      environment:
         - HC3_RELAIS-EXCHANGE_NAME=hc-relais-hat
         - HC3_TEMPERATURE-QUEUE_NAME=hc-temperature
         - HC3_SENSOR_COMBUSTION=28-0214630d20ff
         - HC3_SENSOR_GARAGE=28-03146209ceff
         - HC3_SENSOR_BUFFER=28-0214631220ff
         - RABBITMQ_HOST=hc3-werkstatt
         - RABBITMQ_PORT=5672
      #HEATING-CONTROL_SENSOR_LEADING-LINE=
      #HEATING-CONTROL_SENSOR_RETURN-LINE=
      depends_on:
         - hc3-aqmp
      ports:
         - 8080:8080
      logging:
         driver: "json-file"
         options:
            max-size: "1024m"
      network_mode: "host"
      volumes:
         - /opt/heatingControl/webGui:/webGui
